### ISSUE TITLE
to prevent horizontal resizing of the table

### ISSUE THREAD

**Issue by pankajsikri88** [paulopmx/Flexigrid#11]
hi,
as we know flexigrid allows resizing in horizontal and vertical directions. does anyone have an idea or a fix as to how to disable horizontal resizing while keeping the vertical resizing intact?

TIA

**Comment by paulopmx** [comment]
nohresize : true

**Comment by pankajsikri88** [comment]
hi, 
i commented the below code, does it have any repercussions in the long run?

if (p.resizable && p.width != 'auto' && !p.nohresize) {
            g.rDiv.className = 'hGrip';
            $(g.rDiv).mousedown(function (e) {
                g.dragStart('vresize', e, true);
            }).html('<span></span>').css('height', $(g.gDiv).height());
            if ($.browser.msie && $.browser.version < 7.0) {
                $(g.rDiv).hover(function () {
                    $(this).addClass('hgOver');
                }, function () {
                    $(this).removeClass('hgOver');
                });
            }
            $(g.gDiv).append(g.rDiv);
        }

**Comment by paulopmx** [comment]
it shouldn't.
