### ISSUE TITLE
Custom button caption

### ISSUE THREAD

**Issue by vargabalazs** [paulopmx/Flexigrid#13]
Hy,
I want to add custom button caption.

Example:

buttons : [
&nbsp;&nbsp;&nbsp;&nbsp;{display: 'Hozzáad', name: 'Add', bclass: 'Icon IconAdd', onpress : doCommand},
&nbsp;&nbsp;&nbsp;&nbsp;{display: 'Módosít', name: 'Edit', bclass: 'Icon IconModify', onpress : doCommand},
&nbsp;&nbsp;&nbsp;&nbsp;{display: 'Töröl', name: 'Delete', bclass: 'Icon IconDelete', onpress : doCommand},
&nbsp;&nbsp;&nbsp;&nbsp;{separator: true}
],

I suggest you modify your code

Line 882:
btnDiv.innerHTML = ("&lt;div>&lt;span>") + (btn.hidename ? "&amp;nbsp;" : btn.name) + ("&lt;/span>&lt;/div>");

to 

btnDiv.innerHTML = "&lt;div>&lt;span>" + (btn.display ? btn.display : (btn.hidename ? "&amp;nbsp;" : btn.name)) + "&lt;/span>&lt;/div>";

Bye,
Balázs

**Comment by paulopmx** [comment]
I suggest you fork the rep and request for a pull.

**Comment by vargabalazs** [comment]
Please document:
- What kind of plug do I need?
- Where is it?

I founded jQuery Cookie Plugin by Klaus Hartl

https://github.com/carhartl/jquery-cookie

**Comment by paulopmx** [comment]
The changes where committed by:

https://github.com/rauls

If you want to document it, that's fine. This is an open source project, where forks is the norm.

But I believe the plugin will work without $.cookie plugin. And we are not exactly listing the store/retrieve column feature right now.
