### ISSUE TITLE
Is need cookie plugin?

### ISSUE THREAD

**Issue by vargabalazs** [paulopmx/Flexigrid#14]
$.cookie is not a function
[Break On This Error]   

if( $.cookie(cookie_width) != undefined ) {

flexigrid.js (line 810)

**Comment by paulopmx** [comment]
Yes. It is a plugin.

Some functions will not work, like store and retrieve column widths.

**Comment by vargabalazs** [comment]
It is jQuery Cookie Plugin by Klaus Hartl ?
https://github.com/carhartl/jquery-cookie

**Comment by pankajsikri88** [comment]
u can comment this code.. no issues with the functionality
