### ISSUE TITLE
How to Hide the column in flexgrid

### ISSUE THREAD

**Issue by rkumar670** [paulopmx/Flexigrid#17]
Hi i want to hide the specific column.
how to do that.
thanks.

**Comment by paulopmx** [comment]
In the sample colModel below set hidden to true

colModel : [
        {display: 'ISO', name : 'iso', width : 40, sortable : true, align: 'center', hidden: true}
                ]

**Comment by rkumar670** [comment]
thanks..Solved

**Comment by amitthaper** [comment]
If i want to hide the column on the basis of condition then how can i do this.
