### ISSUE TITLE
How to arrange the json data in a forum kind of format instead of columns

### ISSUE THREAD

**Issue by futurepriya** [paulopmx/Flexigrid#18]
Hi,
In the flexigrid.js, bDiv is the name of the div used to populate the json data by creating html table,tr,td   . I want to modify this bDiv class that is need to populate the json data in forum kind of format..  

Eg:  like in (statck overflow site)

**Comment by paulopmx** [comment]
You want to get rid of the columns?

**Comment by futurepriya** [comment]
yes..   it is exactly like forum kind of thing. Currently  i am using flexigrid , displaying the data in column fashion. Now i need to show the images also. the image url will be sent with json data.

**Comment by paulopmx** [comment]
Why use Flexigrid then? Why not using the native $.ajax of jQuery?

**Comment by futurepriya** [comment]
is native $.ajax , a normal ajax request ?

**Comment by paulopmx** [comment]
It's a normal jQuery function.

http://api.jquery.com/jQuery.ajax/

With it you can create your own html layout on the server, pass it to $.ajax, and place it on any element within the html doc.

**Comment by futurepriya** [comment]
ok thanks. Could you explain how the json data string arranged in to the table of contents? i need to know how the 'bDiv' in flexigrid.js constructed..  i am not able to understand since am new to JQuery

**Comment by paulopmx** [comment]
bDiv is constructed via javascript createElement function during initialization of Flexigrid.

I'm not sure if this is the place to start learning basic jQuery. Start at the link I gave you.
