### ISSUE TITLE
TypeError: $.cookie is not a function 

### ISSUE THREAD

**Issue by cleder** [paulopmx/Flexigrid#33]
TypeError: $.cookie is not a function
    flexigrid.js (line 815) (current version from github, with jQuery  v1.8.0)

if( $.cookie(cookie_width) != undefined ) {

**Comment by nisanov** [comment]
Just include this script in your HTML: https://github.com/carhartl/jquery-cookie/blob/master/jquery.cookie.js

Looks like the same functionality.

**Comment by mabasic** [comment]
Yes but I don't want to include that script in my page, because I don't need it. 
I tried reverting the commits from Raul but no success.
Anyone got a solution ?

**Comment by cleder** [comment]
you could just a) comment those lines out (that's what I did) or b) put a
try, catch around it which I suppose is a valid fix for this

On Thu, Oct 4, 2012 at 6:36 AM, Mario Basic notifications@github.comwrote:

> Yes but I don't want to include that script in my page, because Ii don't
> need it.
> I tried reverting the commits from Raul but no success.
> Anyone got a solution ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/paulopmx/Flexigrid/issues/33#issuecomment-9126193.

## 

Best Regards,

Christian Ledermann

Nairobi - Kenya
Mobile : +254 702978914

<*)))>{

If you save the living environment, the biodiversity that we have left,
you will also automatically save the physical environment, too. But If
you only save the physical environment, you will ultimately lose both.

1) Don’t drive species to extinction

2) Don’t destroy a habitat that species rely on.

3) Don’t change the climate in ways that will result in the above.

}<(((*>

**Comment by mabasic** [comment]
Em, thank you for your answer but I think that that commit should have never been merged in the master branch in the first place.

**Comment by cleder** [comment]
Agreed, at least not in the current form, I was just trying to be pragmatic
and give you and anybody who cares to read the tracker, the pointers to
work around this

On Thu, Oct 4, 2012 at 3:51 PM, Mario Basic notifications@github.comwrote:

> Em, thank you for your answer but I think that that commit should have
> never been merged in the master branch in the first place.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/paulopmx/Flexigrid/issues/33#issuecomment-9134743.

## 

Best Regards,

Christian Ledermann

Nairobi - Kenya
Mobile : +254 702978914

<*)))>{

If you save the living environment, the biodiversity that we have left,
you will also automatically save the physical environment, too. But If
you only save the physical environment, you will ultimately lose both.

1) Don’t drive species to extinction

2) Don’t destroy a habitat that species rely on.

3) Don’t change the climate in ways that will result in the above.

}<(((*>

**Comment by vanderlee** [comment]
Easy & dirty fix; add a dummy "cookie" function to jQuery.

```
if (!jQuery.cookie) {
    jQuery.cookie = function(){};
}
```

Ofcourse such an if statement could (should?) be in flexigrid itself instead.
