### ISSUE TITLE
How to reload colModel ?

### ISSUE THREAD

**Issue by mabasic** [paulopmx/Flexigrid#41]
I want to reload colmodel with different column names. Is it possible ?

**Comment by benbruscella** [comment]
+1

**Comment by joelcarlton** [comment]
Does anyone have any Idea if this can be done? I have a 25+ column table and users may only want to fetch a few relevant columns. I wouldn't even mind passing the colmodel back in the server response and modifying the source to build the headers based on that. 

Can anyone provide a solution that works?

**Comment by ghost** [comment]
I was on the same situation, its just simple hack on flexigrid.js
just comment "if (t.grid) return false; " after function addFlex on flexigrid.js

$.addFlex = function (t, p) {
        //if (t.grid) return false;

and then if you want to reinitialize the flexigrid with different colModel, remove div.flexigrid first and reappend to original tag table

jQuery.fn.exists = function(){return this.length>0;}
$("div.flexigrid").remove();
if(!$("table#flex1").exists()) $("div.dialog_window").append("&lt;table id='flex1' style='display:none'&gt;&lt;/table&gt;");

then

you can define $("table#flex1").flexigrid({ .... });

Just like that...

**Comment by PKanwarpal** [comment]
Hi ardieb77,

We have a similar requirement. Would it be possible  to please share your code snippet which is reloading the grid. 
We have changed the flexigrid slightly (was done by someone else), hence I am figuring out how new colModel should be used for headers. When I set $("div.flexigrid").remove(); the grid just becomes empty when though there is data to load and show. If I only remove the div.hDiv, then multiple headers appear.  Hence, your code snippet would be helpful for us to see if we are missing something. 

Many thanks & kind regards,
Puneet

**Comment by gierg** [comment]
Terima Kasih
