### ISSUE TITLE
How can i set column orders in flexgrid dynamically? 

### ISSUE THREAD

**Issue by rosh18** [paulopmx/Flexigrid#46]
Suppose if a have column a,b and c, the user will shuffle the column as per his requirement lets say b,c,a this value should save in database which i have almost completed. :) Now I want the data to be pulled by ajax call and should be displayed as per the respective users setting. Also I am using .Net 3.5 framework not MVC :)

 Help would be really appreciated. Thanks

**Comment by paulopmx** [comment]
Somebody contributed a column state saving feature which uses $.cookie plugin.

You should be able then to parse the cookie and save the settings in your database.

Then you should be able to to update and create the cookie every time the  user signs in.

**Comment by rosh18** [comment]
I have completed this task using stringbuilder in function and then calling that stringbuilder function through Page.RegisterStartupScript in page load :)
I dont know whether this way is right or wrong but its working fine for me. :)

 protected void Page_Load(object sender, EventArgs e)
        {
            Page.RegisterStartupScript("myFun", CreateJavaScript());
        }

 protected string CreateJavaScript()
        {
            StringBuilder sbString = new StringBuilder();
/*

My piece of code 
sbString.Append("");

*/

}

Also I have another Question and I have created another issue for it 
https://github.com/paulopmx/Flexigrid/issues/48
