### ISSUE TITLE
Holding shift or control key while clicking a row throws an error, solution inside

### ISSUE THREAD

**Issue by uberthold** [paulopmx/Flexigrid#51]
This is because the mouseup event handler in function addRowProp is missing its argument.

Currently it is
}).mouseup(function () {

and should be
}).mouseup(function (e) {

**Comment by daxxog** [comment]
What browser are you on? I do not get an error on the latest Google Chrome.

**Comment by NaomiN** [comment]
I think this (or similar problem) was already discussed. I fixed that
problem locally (because I made few other changes, but I am not using Git).

**Comment by NaomiN** [comment]
BTW, can someone please lend me a hand - I am having troubles implementing
Edit functionality in modal form. I posted my problems in jquery forum (no
replies there) and in ASP.NET forum
http://forums.asp.net/p/1864975/5239799.aspx/1?p=True&t=634910728793808200

**Comment by daxxog** [comment]
WARNING!
Unrelated topic below.

@NaomiN 

I don't use modal forms for editing, instead I just hack flexigrid itself and replace text with inputs. Then you just need a way of reading the inputs and sending the result back to the server. You probably need to give each row an id somehow too.

place this in your edit button click event or whatever

``` javascript
$(grid).find('.trSelected').each(function(i, el) {
    $(el).children().each(function(i, el) {
        var child = $(el).children().children();
        var _chtml = child.html();
        child.html('');

        $('<input></input>').attr({
            'value': _chtml,
            'class': $(el).attr("abbr") + ' editarea',
            'data': JSON.stringify({
                        "col": $(el).attr("abbr")
                    })
        }).css(
            'width', '100%'
        ).appendTo(child);
    });
});
```

**Comment by NaomiN** [comment]
This is a bit tricky, but I also think it would not work for me. In the
grid I only show 4 columns,  but I have a nice form with much more
information.

Also, I am using ASP.NET MVC.

**Comment by daxxog** [comment]
@NaomiN 
Iv'e never touched ASP.NET so I'm not sure I can help you.
Here is an example of modal forms with [jQuery UI](http://jqueryui.com): 
http://jqueryui.com/dialog/#modal-form

**Comment by NaomiN** [comment]
Thanks, this is helpful. I am going to study it more.
