### ISSUE TITLE
Add Data to flex-grid!!!

### ISSUE THREAD

**Issue by LuvG** [paulopmx/Flexigrid#56]
I am using flex-grid in my application. Basically I am building my application in Visual studio 2008 and using C# 3.5. 
My question is How can we add Data in flex-grid in my application!!!
I have a data-table and it has the same 5 columns as one in the demo!!!

**Comment by NaomiN** [comment]
Here is a sample for the beginners using ASP.NET MVC that can get you started. I started from that sample myself
http://mvc4beginner.com/Sample-Code/Insert-Update-Delete/Asp-.Net-MVC-Ajax-Insert-Update-Delete-Using-Flexigrid.html

**Comment by LuvG** [comment]
@NaomiN  Thanks for your reply...but can you help me in implementing the same code without MVC model???
Because i want to deploy my application on Web!!!

**Comment by NaomiN** [comment]
I don't understand why you can not implement something on Web using MVC.
What is your programming language? Also, I think you're posting in the
flexigrid main page and you should be using forums instead.

**Comment by LuvG** [comment]
@NaomiN  i got the solution!!! Thanks for your concern!!!

**Comment by NaomiN** [comment]
Can you please share your solution?

**Comment by daxxog** [comment]
Serialize your data into XML or JSON on the server side and feed the data to to the client over XMLHttpRequest.

It's called [AJAX](http://en.wikipedia.org/wiki/Ajax_(programming) or [REST](http://en.wikipedia.org/wiki/Representational_state_transfer).

## Example 3 from [flexigrid.info](http://flexigrid.info)

``` javascript
$("#flex1").flexigrid({
    url: 'post2.php',
    dataType: 'json',
    colModel : [
        {display: 'ISO', name : 'iso', width : 40, sortable : true, align: 'center'},
        {display: 'Name', name : 'name', width : 180, sortable : true, align: 'left'},
        {display: 'Printable Name', name : 'printable_name', width : 120, sortable : true, align: 'left'},
        {display: 'ISO3', name : 'iso3', width : 130, sortable : true, align: 'left', hide: true},
        {display: 'Number Code', name : 'numcode', width : 80, sortable : true, align: 'right'}
        ],
    buttons : [
        {name: 'Add', bclass: 'add', onpress : test},
        {name: 'Delete', bclass: 'delete', onpress : test},
        {separator: true}
        ],
    searchitems : [
        {display: 'ISO', name : 'iso'},
        {display: 'Name', name : 'name', isdefault: true}
        ],
    sortname: "iso",
    sortorder: "asc",
    usepager: true,
    title: 'Countries',
    useRp: true,
    rp: 15,
    showTableToggleBtn: true,
    width: 700,
    height: 200
});   
```

**Comment by daxxog** [comment]
To me this looks like user error, not a valid flexigrid issue.

**Comment by LuvG** [comment]
thanks @daxxog  for your help!!!
