### ISSUE TITLE
Flexi grid always goto first page when entering page number in goto page

### ISSUE THREAD

**Issue by vibintv** [paulopmx/Flexigrid#57]
Hi
My flexigrid table has 5 pages. If i am in page 3 and try to goto page 5 by entering 5 in goto textbox in flexigrid, it goto page 1.
Similarly when i enter a page number and hit enter from page 1 the number suddenly changed to 1. No ajax call (call to server side) initiated.
I don't know why this happening. Pls help.

**Comment by paulopmx** [comment]
Sorry for the delayed reply. Support is limited in the github pages as other users are more active in the groups.
