### ISSUE TITLE
Flexiuigrid

### ISSUE THREAD

**Issue by ranjitjena** [paulopmx/Flexigrid#65]
Dear sir,
I have update your flexigrid and add some functionality like add,edit, delete etc. Here is the url have a look.
http://flexidemo.ranjitjena.com/

**Comment by paulopmx** [comment]
Hi @ranjitjena,

This is great. I think a lot of user's would benefit from this.

If I may suggest, you can fork Flexigrid, then package this as an optional plugin, as not all projects would need this, and some would probably prefer a smaller payload than features that they don't use.

Also the look and feel need to reflect the them of flexigrid itself.

Just my suggestions.
