### ISSUE TITLE
Filter based on non-data attributes?

### ISSUE THREAD

**Issue by jasonday** [paulopmx/Flexigrid#73]
Is there a method to filter for attributes not defined in the data of the cell.

For example, I have a table set up with events/courses. However, outside of the table I'd like to filter bye beginner, intermediate and advanced courses. These attributes don't exist in the table data.

Is there a method to filter those type of attributes? or make hidden cell data to filter by?

**Comment by NaomiN** [comment]
I think you better ask your question in the forums, not in the issues, Let's continue this discussion there, but just in case, what is your platform?

Perhaps my recent blog post may help http://blogs.lessthandot.com/index.php/WebDev/UIDevelopment/AJAX/asp-net-mvc-project-with

**Comment by jasonday** [comment]
I'll go to the forums, my apologies as it's not really a bug ticket. However, maybe a feature request...

**Comment by gochengz** [comment]
Sorry NaomiN where the link of forum ? icannot found it from this website .. thx
